name: Run Python Scripts and Commit Changes

# on:
#   schedule:
#     - cron: "*/30 * * * *"

# when push on main
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      - name: Run download script
        run: python download.py

      - name: Run generate script
        run: python generate.py

      - name: Commit and push
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
          git remote set-url origin https://${{ secrets.PAT_TOKEN }}@github.com/oxymnds/ctp-langkey.git
          git add -A
          timestamp=$(date -u)
          git commit -m "doc: update $timestamp" --allow-empty
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
