name: Run Python Scripts and Commit Changes

# on:
#   schedule:
#     - cron: "*/30 * * * *"

# when push on main
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      - name: Run download script
        run: python download.py

      - name: Run generate script
        run: python generate.py

      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
          file-path: |
            output/data.csv
            output/en.json
            output/th.json
          commit-msg: Update resources
          github-token: ${{ secrets.GITHUB_TOKEN }}
