name: Run Python Scripts and Open Pull Requests

on:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      # Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      # Execute
      - name: Execute
        run: |
          python download.py
          python generate.py

      # Create branch for new changes
      - name: Create new branch
        run: |
          git checkout -b changes/${{ github.run_number }}
          git add .
          git commit -m "Automated changes"

      # Open a pull request
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "changes/${{ github.run_number }}"
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Automated changes"
          pr_body: "A pull request created by automated job."
