name: Run Python Scripts and Commit Changes

on:
  schedule:
    - cron: "0/30 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      - name: Run download script
        run: python download.py

      - name: Run generate script
        run: python generate.py

      - name: Generate Swift Enums from JSON
        run: python generate_swift_from_json.py output/en.json

      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
          file-path: output/*
          commit-msg: Update resources
          github-token: ${{ secrets.GITHUB_TOKEN }}
